name: Skip Workflow - Push To Main

on:
    push:
        branches:
            - main

jobs:
     build:
        name: Build
        runs-on: ubuntu-latest
        
        steps:
            - name: Build The Code
              run: |
               echo "Build The Code"